version: '3.7'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: nest-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${MYSQL_TZ}
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db